site_name: "Bots Scheduler"
repo_url: https://github.com/dhondta/bots-scheduler
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Robots: robots.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
use_directory_urls: false
markdown_extensions:
  - admonition
  - toc:
      permalink: True
