site_name: "Bots Scheduler"
repo_url: https://github.com/dhondta/bots-scheduler
site_author: dhondta
docs_dir: docs
pages:
  - Introduction: index.md
  - Available jobs: jobs.md
  - How to make a job: howto.md
extra:
  mailto: alexandre.dhondt@gmail.com
theme: readthedocs
extra_javascript:
  - js/collapsible-navbar.js
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
